version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /modules/tchap-translations
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/shared-components
    schedule:
      interval: daily
