name: Build archives and create release for tchap-web on tag "tchap-"

on:
    push:
        tags:
            - "tchap-*"

permissions:
  contents: read

jobs:
    build-archive:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            #Build artifacts for dev, preprod and prod
            - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
            - name: Get Node Version
              id: node_version
              run: echo ::set-output name=node_version::$(node -e 'console.log(require("./package.json").engines.node)')
            - name: Use Node.js ${{ steps.node_version.outputs.node_version }}
              uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
              with:
                  node-version: ${{ steps.node_version.outputs.node_version }}
            - name: Install Dependencies
              run: "yarn install"
            - name: Get Tchap Web Version
              id: version
              run: echo ::set-output name=version::$(node -e 'console.log(require("./package.json").version)')
            - name: Build the archive ${{ steps.version.outputs.version }} for dev
              run: scripts/tchap/package-tchap.sh
              env:
                  CONFIG: dev
            - name: Build the archive ${{ steps.version.outputs.version }} for preprod
              run: scripts/tchap/package-tchap.sh
              env:
                  CONFIG: preprod
            - name: Build the archive ${{ steps.version.outputs.version }} for prod
              run: scripts/tchap/package-tchap.sh
              env:
                  CONFIG: prod
            - name: Get current date
              id: date
              run: echo "::set-output name=date::$(date +'%Y%m%d')"

            #create release
            - name: Create tchap-web release
              uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1.20.0
              with:
                  tag: "tchap-${{ steps.version.outputs.version }}"
                  generateReleaseNotes: true
                  artifacts: >
                      /home/runner/work/tchap-web-v4/tchap-web-v4/tchap-${{ steps.version.outputs.version }}-dev-${{ steps.date.outputs.date }}.tar.gz,
                      /home/runner/work/tchap-web-v4/tchap-web-v4/tchap-${{ steps.version.outputs.version }}-preprod-${{ steps.date.outputs.date }}.tar.gz,
                      /home/runner/work/tchap-web-v4/tchap-web-v4/tchap-${{ steps.version.outputs.version }}-prod-${{ steps.date.outputs.date }}.tar.gz
                  token: ${{ secrets.GITHUB_TOKEN }}
